---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:

      - name: Scripts
        run:
          echo ("testst")
          echo ${{ secrets.DOCKERHUB_USER }}
          echo ${{ secrets.DOCKERHUB_TOKEN }}
          

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: athabti #${{ secrets.DOCKERHUB_USER }}
          password: dckr_pat_A3UO7w8lg7bW-W1OkBdQHkdWOZs #${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
